name: 👷‍♂️ Auto-Assign Issues and PRs
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
      with:
        egress-policy: audit

    - name: '👷‍♂️ Auto-assign Issue'
      uses: pozil/auto-assign-issue@21ffb634481e75f2557e5f507e359cba97bbc42b # v2
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          numOfAssignee: 1
          assignees: ${{ vars.DEFAULT_ISSUE_ASSIGNEE }}
          allowSelfAssign: true
    - name: '👷‍♂️ Auto-assign PR'
      uses: pozil/auto-assign-issue@21ffb634481e75f2557e5f507e359cba97bbc42b # v2
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          numOfAssignee: 1
          assignees: ${{ vars.DEFAULT_PR_ASSIGNEE }}
          allowSelfAssign: true
