name: 👷‍♂️ Auto-Assign Issues and PRs
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
      with:
        egress-policy: audit

    - name: '👷‍♂️ Auto-assign Issue'
      uses: pozil/auto-assign-issue@7bf9d82c77d45976224660b873fc83e60576c5aa # v2
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          numOfAssignee: 1
          assignees: ${{ vars.DEFAULT_ISSUE_ASSIGNEE }}
          allowSelfAssign: true
    - name: '👷‍♂️ Auto-assign PR'
      uses: pozil/auto-assign-issue@7bf9d82c77d45976224660b873fc83e60576c5aa # v2
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          numOfAssignee: 1
          assignees: ${{ vars.DEFAULT_PR_ASSIGNEE }}
          allowSelfAssign: true
