name: 👷 Build Module
on:
  pull_request:
    branches:
      - main
      - prerelease
    paths:
      - "src/PSPreworkout/**"
      - "src/Tests/**"
      - "src/PSPreworkout.build.ps1"
      - "src/PSPreworkout.Settings.ps1"
      - "src/PSScriptAnalyzerSettings.psd1"
      - ".github/workflows/Build Module.yml"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: 🧪 Run Tests and Build
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    # strategy:
    #  fail-fast: false

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: ✅ Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🥾 Bootstrap
        shell: pwsh
        run: .\src\actions_bootstrap.ps1

      - name: 👷‍♂️ Test and Build
        shell: pwsh
        run: Invoke-Build -File .\src\PSPreworkout.build.ps1

      - name: 🧪 Upload Pester Results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: pester-results
          path: .\src\Artifacts\testOutput
          if-no-files-found: warn

      - name: 📦 Upload Build
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: zip-archive
          path: .\src\Archive
          if-no-files-found: warn
