name: 📚 Create External Help

on:
  # Run after the 'Build Module' workflow completes.
  workflow_run:
    workflows: ["Build Module", "👷 Build Module"]
    types:
      - completed

  # Run after a push to the main branch changes files in the '/docs' directory or subdirectories.
  push:
    branches:
      - main
    paths:
      - "docs/**"

  # Allows manual triggering of the workflow
  workflow_dispatch:

permissions:
  contents: read # Required to read the repository contents

jobs:
  package_help:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    # The New-ExternalHelpCab cmdlet uses makecab, which depends on Windows.
    runs-on: windows-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: ✅ Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: 📖 Generate External Help XML
        shell: pwsh
        run: |
          Install-Module -Name PlatyPS -Scope CurrentUser -Force
          Import-Module -Name PlatyPS

          $moduleName = "PSPreworkout"
          $moduleManifestPath = ".\src\PSPreworkout\PSPreworkout.psd1"
          $moduleManifest = Test-ModuleManifest -Path $moduleManifestPath -ErrorAction Stop

          Import-Module -Name $moduleManifestPath -Force

          $markdownOutputFolder = ".\src\Artifacts\docs"
          $externalHelpOutputFolder = ".\src\Artifacts\en-US"

          New-Item -Path $markdownOutputFolder -ItemType Directory -Force | Out-Null
          New-Item -Path $externalHelpOutputFolder -ItemType Directory -Force | Out-Null

          $markdownParams = @{
              Module         = $moduleName
              OutputFolder   = $markdownOutputFolder
              Force          = $true
              WithModulePage = $true
              Locale         = "en-US"
              FwLink         = "NA"
              HelpVersion    = $moduleManifest.Version.ToString()
          }

          New-MarkdownHelp @markdownParams
          New-ExternalHelp -Path $markdownOutputFolder -OutputPath $externalHelpOutputFolder -Force

      - name: 📦 Package External Help
        shell: pwsh
        run: |
          Write-Host "${{ github.event.repository.name }}" -ForegroundColor Green
          Write-Host "Current Directory: $PWD" -ForegroundColor Cyan

          Import-Module -Name PlatyPS

          $params = @{
              CabFilesFolder  = ".\src\Artifacts\en-US"  # Source XML folder.
              LandingPagePath = ".\docs\PSPreworkout.md" # Path to the landing page.
              OutputFolder    = ".\docs\en-US"           # Actual output folder.
          }
          New-ExternalHelpCab @params
