name: 📖 Deploy Zensical Docs to GitHub Pages

on:
  # Run when changes are made to the docs content, docs dependencies, workflow, or config.
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/Deploy Zensical.yml"
      - "mkdocs.yml"

  # Allow manual triggering of the workflow.
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: ✅ Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 🐍 Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.12"

      - name: ➕ Install Zensical
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: 👷‍♂️ Deploy Zensical Docs to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: zensical gh-deploy --force
