name: 🏷️ Publish Prerelease Version
# Publish a prerelease version when a pull request is merged into the 'prerelease' branch.
# This workflow automatically increments the version with a prerelease suffix and publishes to PowerShell Gallery.

on:
  pull_request:
    branches:
      - prerelease
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prerelease:
    name: 🚀 Build and Publish Prerelease
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔧 Generate Prerelease Version
        id: version
        shell: pwsh
        run: |
          try {
            # Read current version from manifest
            $manifestPath = ".\src\PSPreworkout\PSPreworkout.psd1"
            if (-not (Test-Path $manifestPath)) {
              throw "Module manifest not found at: $manifestPath"
            }
            
            $manifest = Import-PowerShellDataFile -Path $manifestPath
            $currentVersion = $manifest.ModuleVersion
            
            Write-Host "Current version: $currentVersion" -ForegroundColor Green
            
            # Generate prerelease suffix with timestamp
            $timestamp = Get-Date -Format "yyyyMMddHHmm"
            $prereleaseVersion = "$currentVersion-preview.$timestamp"
            
            Write-Host "Prerelease version: $prereleaseVersion" -ForegroundColor Yellow
            
            # Update manifest with prerelease version
            $manifestContent = Get-Content -Path $manifestPath -Raw
            
            # Update the Prerelease field - look for commented line
            if ($manifestContent -match '#\s*Prerelease\s*=\s*[^#\r\n]*') {
              $manifestContent = $manifestContent -replace '#\s*Prerelease\s*=\s*[^#\r\n]*', "Prerelease = 'preview.$timestamp'"
              Write-Host "Updated commented Prerelease line" -ForegroundColor Green
            } elseif ($manifestContent -match "Prerelease\s*=\s*'[^']*'") {
              $manifestContent = $manifestContent -replace "Prerelease\s*=\s*'[^']*'", "Prerelease = 'preview.$timestamp'"
              Write-Host "Updated existing Prerelease line" -ForegroundColor Green
            } else {
              # Add Prerelease field after the comment
              $manifestContent = $manifestContent -replace "(# Prerelease string of this module)", "`$1`n            Prerelease = 'preview.$timestamp'"
              Write-Host "Added new Prerelease line" -ForegroundColor Green
            }
            
            # Save updated manifest
            Set-Content -Path $manifestPath -Value $manifestContent -Encoding UTF8
            
            # Verify the change by parsing the updated manifest
            $updatedManifest = Import-PowerShellDataFile -Path $manifestPath
            $actualPrerelease = $updatedManifest.PrivateData.PSData.Prerelease
            
            if ($actualPrerelease -eq "preview.$timestamp") {
              Write-Host "Successfully updated manifest prerelease: $actualPrerelease" -ForegroundColor Green
            } else {
              throw "Failed to update prerelease field. Expected: 'preview.$timestamp', Got: '$actualPrerelease'"
            }
            
            # Set outputs for later steps
            "PRERELEASE_VERSION=$prereleaseVersion" >> $env:GITHUB_OUTPUT
            "BASE_VERSION=$currentVersion" >> $env:GITHUB_OUTPUT
            "PRERELEASE_SUFFIX=preview.$timestamp" >> $env:GITHUB_OUTPUT
            
          } catch {
            Write-Error "Failed to generate prerelease version: $($_.Exception.Message)"
            throw
          }

      - name: 🚀 Publish to PowerShell Gallery
        shell: pwsh
        env:
          NUGET_API_KEY: ${{ secrets.POWERSHELLGALLERY_KEY }}
        run: |
          try {
            Write-Host "Publishing prerelease module to PowerShell Gallery..." -ForegroundColor Cyan
            
            # Verify API key is available
            if (-not $env:NUGET_API_KEY) {
              throw "PowerShell Gallery API key not found in secrets"
            }
            
            # Set repository as trusted
            Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
            
            # Publish the module with prerelease support
            $publishParams = @{
              Path = '.\src\Artifacts\PSPreworkout'
              NuGetApiKey = $env:NUGET_API_KEY
              Repository = 'PSGallery'
              Force = $true
              AllowPrerelease = $true
              Verbose = $true
            }
            
            Write-Host "Publishing with parameters:" -ForegroundColor Yellow
            $publishParams | Out-String | Write-Host
            
            Publish-Module @publishParams
            
            Write-Host "Successfully published prerelease version: ${{ steps.version.outputs.PRERELEASE_VERSION }}" -ForegroundColor Green
            
          } catch {
            Write-Error "Failed to publish module: $($_.Exception.Message)"
            Write-Host "Error details: $($_.Exception)" -ForegroundColor Red
            throw
          }

      - name: 📝 Create Release Notes
        shell: pwsh
        run: |
          $version = "${{ steps.version.outputs.PRERELEASE_VERSION }}"
          $releaseNotes = @"
          # PSPreworkout $version (Prerelease)
          
          This is a prerelease version of PSPreworkout automatically published from the prerelease branch.
          
          **Version**: $version
          **Branch**: prerelease
          **Commit**: ${{ github.sha }}
          
          ## Installation
          
          To install this prerelease version:
          ``````powershell
          Install-Module -Name PSPreworkout -AllowPrerelease -Force
          ``````
          
          ## Notes
          
          - This is a prerelease version and may contain experimental features
          - Use at your own risk in production environments
          - Feedback and bug reports are welcome
          
          "@
          
          Write-Host "Release notes created for version $version" -ForegroundColor Green
